### ISSUE TITLE
Using face keypoints in the skeletal model

### ISSUE THREAD

**Issue by divyachhipani** [gopeith/SignLanguageProcessing#1]
Hi, 

I wanted to know if there is any way to accomodate the facial keypoints in the skeletal model. I did read the paper where you mentioned about encorporating facial expressions. Looking forward to your response.

Thanks,
Divya

**Comment by gopeith** [comment]
Hi,
There are two different answers:
1) Yes, facial features could be flawlessly incorporated into sign language production as additional output features. The only one small catch is that faces and facial expressions are obviously highly distinctive.
2) No, if you mean our 2D->3D conversion. The reason is that used backpropagation requires a tree-like structure and the facial keypoints make several cycles. Furthermore, a face is partially elastic and not a skeleton with solid bones.

**Comment by divyachhipani** [comment]
Hi,

Thanks for your reply. Is there any other way for 2D to 3D conversion for
facial keypoints?
