### ISSUE TITLE
Regarding ^C error on google colab during 3D pose estimation

### ISSUE THREAD

**Issue by divyachhipani** [gopeith/SignLanguageProcessing#2]
Hi,

I am running the file pipeline_demo_02_filter.py on the output from part 1. I have 201 keys in .h5 file and after processing half of the batch i.e 100, I encounter ^C on Google Colab. I reduced the number of keys to 67, and the issue was reproduced at 34th file. I can assure you that I haven't pressed ^C. Googling the issue, I find out that it is an out of memory issue but I don't think that is the case if initially it was able to process 100 files. I also ran the code on Google Colab Pro, but I still get the issue. Would you by any chance know why is this the case?

Thanks,
Divya

**Comment by gopeith** [comment]
Hi,
I'm sorry that I've forgotten to mention this issue before. Some people report the same thing. I might be wrong but the reason is very probable some memory leak in the Keras backend or in TensorFlow itself and I can't solve it directly on my end. However, running the script on smaller bunches will solve it. There is also another solution that works sometime: limit the number of CPUs, i.e. add this code

conf = tf.ConfigProto(
    device_count={'CPU': 1},
    intra_op_parallelism_threads=1,
    inter_op_parallelism_threads=1,
  )
K.set_session(tf.Session(config=conf))

**Comment by divyachhipani** [comment]
Thanks for sharing!
